spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/toy
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  logging.level:
    org.hibernate.SQL: debug
    org.apache.coyote.http11: trace
  profiles:
    active: local



file:
  dir: C:/ToyprojectUploadFileRoot/