spring:
  #gmail
#  mail:
#    host: smtp.gmail.com                #이메일 서버의 호스트명 (여기서는 Gmail의 SMTP 서버)
#    port: 587                           #Gmail의 경우 587
#    username: simseo034@gmail.com     #Gmail 계정 아이디
#    password: ccqs vdnt ttlm uspc
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#            required: true
#        debug: true
#        connectiontimeout: 5000
#        timeout: 5000
#        writetimeout: 5000

#  mail:
#    host: smtp.naver.com                #이메일 서버의 호스트명 (여기서는 naver SMTP 서버)
#    port: 587                           #Gmail의 경우 587
#    username: zxcqew32@naver.com     #Gmail 계정 아이디
#    password: penguwithdonkey
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#            required: true
#        debug: true
#        connectiontimeout: 5000
#        timeout: 5000
#        writetimeout: 5000
  mail:
    host: smtp.kakao.com                #이메일 서버의 호스트명 (여기서는 Gmail의 SMTP 서버)
    port: 465                           #Gmail의 경우 587
    username: zxcqew32@kakao.com     #Gmail 계정 아이디
    password: bunwoo5%5%
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          auth: true
          starttls:
            enable: true
            required: true
        debug: true
        connectiontimeout: 5000
        timeout: 5000
        writetimeout: 5000
#smtp.ssl.enable=true
#properties.mail.smtp.auth=trues

  #h2:
  #  console:
  #    enabled: true

  datasource:
    url: jdbc:h2:tcp://localhost/~/toy
    driver-class-name: org.h2.Driver
    username: sa
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  logging.level:
    org.hibernate.SQL: debug
    org.apache.coyote.http11: trace
  profiles:
    active: local

file:
  dir: C:/BWProject/toyProject/boardFile/

naver:
  key:
    client_id: ol6ufIkPouDkI1SwOF_x
    client_secret: jiPERDkQiD